// <auto-generated />
using System;
using CmsProject.Templates.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CmsProject.Templates.Infrastructure.Migrations
{
    [DbContext(typeof(TemplateContext))]
    [Migration("20210427143453_migration_03")]
    partial class migration_03
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CmsProject.Templates.Domain.CSS", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CaminhoArquivoCss")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("HistoricoCssFileId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdPagina")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Workflow")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HistoricoCssFileId");

                    b.ToTable("CSS");
                });

            modelBuilder.Entity("CmsProject.Templates.Domain.HistoricoPorPagina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdPagina")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("HistoricoPorPagina");
                });

            modelBuilder.Entity("CmsProject.Templates.Domain.Imagens", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CaminhoImagem")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdPagina")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Imagens");
                });

            modelBuilder.Entity("CmsProject.Templates.Domain.Paginas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Body")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid?>("CssId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Footer")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Header")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid?>("HistoricoPaginaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ImagensId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Javascript")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Menu")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("WorkFlow")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CssId");

                    b.HasIndex("HistoricoPaginaId");

                    b.HasIndex("ImagensId");

                    b.ToTable("Paginas");
                });

            modelBuilder.Entity("CmsProject.Templates.Domain.CSS", b =>
                {
                    b.HasOne("CmsProject.Templates.Domain.HistoricoPorPagina", "HistoricoCssFile")
                        .WithMany()
                        .HasForeignKey("HistoricoCssFileId");
                });

            modelBuilder.Entity("CmsProject.Templates.Domain.Paginas", b =>
                {
                    b.HasOne("CmsProject.Templates.Domain.CSS", "Css")
                        .WithMany()
                        .HasForeignKey("CssId");

                    b.HasOne("CmsProject.Templates.Domain.HistoricoPorPagina", "HistoricoPagina")
                        .WithMany()
                        .HasForeignKey("HistoricoPaginaId");

                    b.HasOne("CmsProject.Templates.Domain.Imagens", "Imagens")
                        .WithMany()
                        .HasForeignKey("ImagensId");
                });
#pragma warning restore 612, 618
        }
    }
}
