// <auto-generated />
using System;
using CmsProject.Templates.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CmsProject.Templates.Infrastructure.Migrations
{
    [DbContext(typeof(TemplateContext))]
    partial class TemplateContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CmsProject.Templates.Domain.BackupElementoFrontEnd", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ElementoFrontEndId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdElementoFrontEnd")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ElementoFrontEndId");

                    b.ToTable("BackupElementoFrontEnd");
                });

            modelBuilder.Entity("CmsProject.Templates.Domain.BackupPagina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdPagina")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PaginaId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PaginaId");

                    b.ToTable("BackupPagina");
                });

            modelBuilder.Entity("CmsProject.Templates.Domain.ElementoFrontEnd", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CaminhoArquivo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Conteudo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EhArquivoFisico")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("IdPagina")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid?>("PaginaId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Workflow")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaginaId");

                    b.ToTable("ElementoFrontEnd");
                });

            modelBuilder.Entity("CmsProject.Templates.Domain.Imagens", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CaminhoImagem")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Conteudo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EhArquivoFisico")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid?>("PaginaId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("PaginaId");

                    b.ToTable("Imagens");
                });

            modelBuilder.Entity("CmsProject.Templates.Domain.Pagina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Body")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Footer")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Header")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("char(36)");

                    b.Property<string>("Menu")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("TemplatesId")
                        .HasColumnType("char(36)");

                    b.Property<int>("WorkFlow")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemplatesId");

                    b.ToTable("Paginas");
                });

            modelBuilder.Entity("CmsProject.Templates.Domain.Templates", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("CmsProject.Templates.Domain.BackupElementoFrontEnd", b =>
                {
                    b.HasOne("CmsProject.Templates.Domain.ElementoFrontEnd", "ElementoFrontEnd")
                        .WithMany("BackupElementoFrontEnd")
                        .HasForeignKey("ElementoFrontEndId");
                });

            modelBuilder.Entity("CmsProject.Templates.Domain.BackupPagina", b =>
                {
                    b.HasOne("CmsProject.Templates.Domain.Pagina", "Pagina")
                        .WithMany("BackupPagina")
                        .HasForeignKey("PaginaId");
                });

            modelBuilder.Entity("CmsProject.Templates.Domain.ElementoFrontEnd", b =>
                {
                    b.HasOne("CmsProject.Templates.Domain.Pagina", "Pagina")
                        .WithMany("ElementoFrontEnd")
                        .HasForeignKey("PaginaId");
                });

            modelBuilder.Entity("CmsProject.Templates.Domain.Imagens", b =>
                {
                    b.HasOne("CmsProject.Templates.Domain.Pagina", "Pagina")
                        .WithMany("Imagens")
                        .HasForeignKey("PaginaId");
                });

            modelBuilder.Entity("CmsProject.Templates.Domain.Pagina", b =>
                {
                    b.HasOne("CmsProject.Templates.Domain.Templates", "Templates")
                        .WithMany("Pagina")
                        .HasForeignKey("TemplatesId");
                });
#pragma warning restore 612, 618
        }
    }
}
