// <auto-generated />
using System;
using CmsProject.Usuarios.Infraestrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CmsProject.Usuarios.Infraestrutura.Migrations
{
    [DbContext(typeof(UsuariosContexts))]
    [Migration("20200917141649_03_migration_sistemas")]
    partial class _03_migration_sistemas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CmsProject.Usuarios.Domain.Sistemas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Status")
                        .HasColumnName("tinyint")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Sistemas");
                });

            modelBuilder.Entity("CmsProject.Usuarios.Domain.Usuarios", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<sbyte>("Ativo")
                        .HasColumnName("ativo")
                        .HasColumnType("tinyint");

                    b.Property<string>("CPF_CNPJ")
                        .IsRequired()
                        .HasColumnName("cpf_cnpj")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DataCancelamento")
                        .HasColumnName("dataCancelamento")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnName("dataCriacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataRetorno")
                        .HasColumnName("dataRetorno")
                        .HasColumnType("datetime");

                    b.Property<Guid>("IdSistema")
                        .HasColumnName("idSistema")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SobreNome")
                        .IsRequired()
                        .HasColumnName("sobrenome")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .HasColumnName("status")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TipoUsuario")
                        .HasColumnName("tipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios_system");
                });
#pragma warning restore 612, 618
        }
    }
}
